### ISSUE TITLE
When uploading pose keypoints via api in coco, it expects deleted keypoints

### ISSUE THREAD

**Issue by hartwoolery** [roboflow/roboflow-python#321] opened 2024-08-29 03:34 UTC
when you create the classes for pose in roboflow you can delete a keypoint from your template.  however, these deleted keypoints are expected to be present in the data when you upload to roboflow via api, otherwise your keypoints will be out of order
![Screenshot 2024-08-28 at 8 32 51 PM](https://github.com/user-attachments/assets/7f7dc73c-71fb-4e83-b0a0-9395996bffc3)

**Comment by yeldarby** [comment] 2024-08-29 03:56
That’s a good point. What format are you uploading in?

 Do you already have existing data in your dataset? The reason we keep them is so it’s non-destructive if you delete a point here you can restore it on all your images since it has a uniquely referenced ID

I wonder if we need a config for whether your skeleton matches the full historical one or the current state.

Do you have a desired behavior?

**Comment by hartwoolery** [comment] 2024-08-29 04:08
Makes sense!  I'm uploading it in coco format - I think that's the only supported one.  IMO the default behavior should be to assume new uploads match the current state of the skeleton, so perhaps have the client or backend check the state and fill in the blanks.

**Comment by yeldarby** [comment] 2024-08-29 04:11
Yeh I think that makes sense. We will have a look at this before the end of the week and let you know when it’s fixed/deployed.

**Comment by yeldarby** [comment] 2024-09-03 17:24
(Sorry; following up that I didn't get to this last week & am diving in this afternoon)

**Comment by yeldarby** [comment] 2024-09-03 20:00
Update: I was able to reproduce this in my staging environment. Looking into how to fix w/o also breaking any happy paths.

**Comment by SolomonLake** [comment] 2024-09-05 16:45
@yeldarby and I have pushed a fix for this issue to our API. When you upload annotation data via the API or front-end UI we now make sure the keypoints are in order!

We try to detect and handle both cases where there are keypoints equal to the number of non-deleted points in your existing skeleton, and where you have padded the array with deleted points.

I'm going to close as completed, @hartwoolery if you experience more issues with this let me know and I'll re-open! Thank you for reporting this issue!

**Closed by SolomonLake** 2024-09-05 16:45 UTC
